### PR TITLE
Update exposure model v2023.1.0

### PR DESCRIPTION
**Pull request by CatalinaYepes**
Update exposure model with GEM global model release June 2023. It includes:
<ul><li>The USA model updated with FEMA 2023</li><li>Turkey updated after M7.8_Kahramanmaras-Gaziantep earthquake</li><li>Minor adjustment to ensure consistent boundary names</li><li>Minor adjustments in taxonomy strings for additional GEM vulnerability functions.</li></ul>

Polish home readme

### CODE REVIEW

**Comment by nicolepaul** [comment]
I will paste here the release notes from the internal repos. I suggest the table in the readme be slightly adjusted to match these, but I'll let you choose the level of detail. 

Note that the major USA model update is per [USACE NSI](https://www.hec.usace.army.mil/confluence/nsi), although the model is a hybrid between USACE NSI, HAZUS, and FEMA 366. 

The notes on spatial disaggregation are not relevant to the files shared publicly. Also, I believe most of the revisions to incorporate the new vulnerability classes (e.g., WBB, NSCA) are on the taxonomy mapping file and not the exposure CSV files. Therefore, those updates may similarly not be relevant to this repo.

# Exposure (General) notes
> Exposure models corresponding to the official June 2023 release of the Global Risk Model. Occupants are distributed across day, night, transit, and average time periods to facilitate fatality estimation. Specific country updates, as denoted in each regional exposure repo release table. Introduction of several new vulnerability classes, including WBB (bamboo), INF (informal/light wood), VL100 (high collapse volume loss), RWO (lightweight roof), NSCA (nonstructural/contents anchored).

# Notes by region
| Region                    | Release Notes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|---------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Africa                    | Aggregated exposure files were added. The disaggregation process is slightly different to conform to the GRM standard. Taxonomy maps for North African countries were differentiated to allow Sub-Saharan countries to explicitly note lightweight roofs for adobe block structures. The taxonomy map for Sub-Saharan Africa also now references new WBB and INF vulnerability classes.                                                                                                                                                                       |
| Caribbean_Central_America | Spatial disaggregation of exposure for most countries. Individual taxonomy mapping files provided for each Central American country, differentiating roof weight on adobe structures relative to the Caribbean countries. More low ductility and high collapse volume classes assigned to HTI in the taxonomy map. The taxonomy maps were also adjusted to incoporate the new WBB and INF vulnerability classes. Some tags for ID_1 fixed for CYM and TCA.                                                                                                    |
| Central_Asia              | Minor update relative to v2023.0.0. Aggregated and disaggregated exposure now included. Light roofs are additionally considered for 25% of adobe block buildings.                                                                                                                                                                                                                                                                                                                                                                                             |
| East_Asia                 | Aggregated and disaggregated exposure added. For Japan, NSCA taxonomy substrings were added to denote anchored nonstructural components and contents and taxonomy strings were harmonized across occupancy classes. For China, revisions were made to the taxonomy mapping CSV, increasing the fraction of non-ductile and soft-storey concrete buildings and high collapse volume loss buildings. For Taiwan, the taxonomy map was revised for residential and commercial buildings.                                                                         |
| Europe                    | Exposure was spatially disaggregated for many countries. Revised taxonomy map. Specific updates for Turkey and Switzerland. For Turkey, buildings that collapsed in the 2023 earthquakes were removed, mixed occupancy classes were defined, and the taxonomy map was revised to increase soft-storeys, non-ductile concrete classes, and high collapse volume loss buildings. For Switzerland, floor areas and costs were updated with consideration of the ERM-CH23 model. For Italy, the masonry unit types used in residential construction was changed.  |
| Middle_East               | Aggregated versions of the exposure models included. In Iran, the amount of residential buildings with low ductility was slightly increased (approximately 5% nationwide). In both Iran and Armenia, more high collapse volume buildings were added.                                                                                                                                                                                                                                                                                                          |
| North_America             | Major update for USA and CAN. USA is based on the USACE/NSI exposure model, with some modifications. CAN is based on the NRCan exposure model, with some modifications. MEX taxonomy map was revised to denote roof weights on adobe structures, references to the new WBB and INF vulnerability classes, and to increase the amount of MCF.                                                                                                                                                                                                                  |
| North_Asia                | Improvement to taxonomy strings for Mongolia. Aggregated and disaggregated exposure files added. For Russia, high collapse volume loss buildings were added to the taxonomy map.                                                                                                                                                                                                                                                                                                                                                                              |
| Oceania                   | Aggregated and disaggregated exposure files included. Lightweight roofs assigned to adobe buildings for the PNG and Oceania taxonomy mapping files. Additionally, the new WBB and INF vulnerability classes are referenced in the taxonomy maps                                                                                                                                                                                                                                                                                                               |
| South_America             | Adjustments to the mapping schemes for adobe classes. Additionally, the taxonomy map was revised to reflect the distribution of light versus heavy roofs for adobe buildings and to incorporate the new WBB and INF vulnerability classes. Spatial disaggregation was run, but only for the admin areas where refined exposure was not available from local projects in Colombia, Ecuador, and Chile.                                                                                                                                                         |
| South_Asia                | Aggregated and disaggregated exposure files added. Roof weights for adobe structures are updated for AFG, BGD, IND, and PAK. Both IND and BGD use light-weight roofs (RWO) for 100% of adobe buildings, AFG and PAK for 80%. Additionally, new vulnerability classes for WBB and INF were incorporated into the taxonomy maps for BGD, IND, NPL, and PAK. New high collapse volume loss variants VL100 were also considered in the taxonomy map for NPL.                                                                                                      |
| Southeast_Asia            | Aggregated and disaggregated exposure files added. Minor adjustment to ensure consistent boundary names for Myanmar. The taxonomy maps for IDN, PHL, MMR, and TLS were updated to consider new WBB and INF vulnerability classes.                                                                                                                                                                                                                                                                                                                             |

**Comment by nicolepaul** [comment]
Additionally, depending on how we decide to incorporate the new internal repo structure (including the **Metadata** folder), we may decide to make this release `v2023.1.1` rather than `v2023.1.0`.

**Review by raoanirudh — APPROVED** [review]

**Comment by nicolepaul** [comment]
Release notes and mapping scheme files require updates for:

- Switzerland
- Italy
- Turkey
- Japan
- Taiwan
- Ecuador
- Argentina

I will add the Africa mapping schemes also, so that we can deprecate the [africa-exposure-model](https://github.com/nicolepaul/africa-exposure-model) and redirect towards this one.

**Comment by CatalinaYepes** [comment]
Model version notes updated as well as mapping files for Ecuador and Argentina.

Most of the changes reflected in the release notes of the internal repos refer to modifications in the taxonomy mapping file that relates exposure to vulnerability, which is a following step when assessing earthquake risk.

**Pull request merged**
